FROM oven/bun:alpine AS base

  # 1. Install dependencies only when needed
FROM base AS deps
  # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.

WORKDIR /app
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
